### ISSUE TITLE
Create Service to download latest motion recording video

### ISSUE THREAD

**Issue by briis** [briis/securityspy#12]
Create a service, that can download the latest Motion Recording video stored on SecuritySpy. This can be used in Notifications or just saved on Home Assistant.

**Comment by divemasterjm** [comment]
+1

**Comment by briis** [comment]
There is now a new service called `securityspy.download_latest_motion_recording` It takes two parameters: 
* `entity_id`: Specify the camera to get the recording for 
* `filename`: Specify the location where you want to store the video file.

Here is an example:

```yaml
service: securityspy.download_latest_motion_recording
data:
  entity_id: camera.kamera_carport
  filename: /config/www/carport_latest.m4v
```

A very basic example of use is this, where we download the video, when motion recording goes from on to off (When it is off, we know that the file is written to SecuritySpy)

```yaml
alias: Download Recording after motion
description: ''
trigger:
  - platform: state
    entity_id: binary_sensor.motion_kamera_carport
    from: 'on'
    to: 'off'
condition: []
action:
  - service: securityspy.download_latest_motion_recording
    data:
      entity_id: camera.kamera_carport
      filename: /config/www/carport_latest.m4v
mode: single
```
