### ISSUE TITLE
Feature Request: Camera Online Sensor

### ISSUE THREAD

**Issue by julianrinaldi** [briis/securityspy#22]
It would be nice to have a boolean sensor to show if a camera is online/offline. I have a couple of cheap wifi cameras for random things around the house that annoyingly go offline every so often, and which can be fixed by power cycling a smart switch. It would be nice to be able to use a boolean sensor to trigger that to happen automatically if they're offline for a few minutes.

**Comment by briis** [comment]
The online status is already present. If you look at the Attributes for the camera entity, there is an attribute called `online` which is either true or false. You could easy check for that in an automation and do what you need to do. Below is the *Trigger* part of an automation for a camera called `camera.carport` that will run when online is going to `false`. You then have to fill in the Action part of that automation.

Would that work for you, instead of me creating a new sensor.

```yaml
alias: Do something when camera goes offline
description: ''
mode: single
trigger:
  - platform: state
    entity_id: camera.carport
    attribute: online
    to: 'false'
condition: []
action:
  - service: DO SOMETHING HERE
    data: {}
````
