### ISSUE TITLE
trigger to human  or veichle don't work

### ISSUE THREAD

**Issue by nico1495** [briis/securityspy#75]
Hi, I'm trying to write an automation that sends a telegram notification when a Human is detected. I'm sure the code works because the "action" part works great on another automation. I think this integration has some problems. Or am I doing something wrong?

```
alias: Capture snapshot when person is detected
description: ''
trigger:
  - platform: state
    entity_id: binary_sensor.esterna_motion
    attribute: event_object
    to: human
# condition: []
action:
  - service: notify.nico
    data_template:
      message: "ripresa esterna"
      data:
        photo:
          - url: 'http://test.local:8000/image?cameraNum=0&auth=!525a9d9d1680bfec77c398ab5d2279d703c3216cf31f95b8'
            caption: "test human"  {{now().strftime("%d.%m.%y - %H:%M:%S")}}  
```
